# .bandit.yml
exclude_dirs: ['tests', '.venv', '.git', '__pycache__', '.pytest_cache', 'instance']
skips: ['B101', 'B404', 'B105']  # B105 пропускаем, так как проверяем в отдельном шаге
targets: ['*.py']

# Уровни проверки
confidence_level: 'MEDIUM'
severity_level: 'MEDIUM'

# Исключения
exclude: ['bad_example.py']